#+TITLE: My Emacs Configuration

My personal Emacs setup.

* Influences

- [[https://github.com/hlissner/doom-emacs][Doom Emacs]]
- [[https://github.com/seagle0128/.emacs.d][Centaur Emacs]]
- [[https://github.com/angrybacon/dotemacs][AngryBacon's Emacs Configuration]]
- [[https://svn.red-bean.com/repos/kfogel/trunk/.emacs][kfogel's .emacs]]
- [[https://github.com/alphapapa/unpackaged.el][alphapapa's unpackaged.el]]

* My Thought Process

You'll notice a lot of things are taken from Doom, bits from Centaur Emacs, and some other Emacs
users' configurations and stuff from the [[https://old.reddit.com/r/emacs][r/emacs subreddit]] (which I try to give links to).
A lot of helper functions and hooks I take from Doom, due to letting some better organizing
and deferring of packages.

Part of why I move away from Doom is that, while it's a /great/ setup for Emacs, I found the part of
it being a framework made some things a bit more complicated. You're not just having to potentially
debug package errors, you're also having to debug Doom Emacs functions and macros, etc.
And when running into issues, figuring out what is causing the issue becomes a bit more complicated
than it already can be when it comes to Emacs.

I also just wanted something that felt like my own, and to use /some/ of the preexisting functionality
found in Emacs.

* TODO Things I'd like to do

- [ ] My own code formatter
- [ ] Actually implement the splash screen
- [ ] Add in more sources for consult
- [ ] Refactor some of the Doom functions/helpers using builtin functionality
